services:
  api:
    container_name: api
    image: poulejnar/sw4fed-modelsapi:v2
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      feddb:
        condition: service_healthy
    environment:
      Connectionstrings__DefaultConnection: "Server=feddb;Database=FED-Assignment2;User Id=SA;Password=YourStrong@Passw0rd;MultipleActiveResultSets=True;TrustServerCertificate=True"
      ASPNETCORE_HTTPS_PORTS: 8081
      ASPNETCORE_Kestrel__Certificates__Default__Password: StrongPassw0rd!
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/ModelsApi.pfx
  feddb:
    container_name: feddb
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    user: root
    volumes:
      - fed-assignment2:/var/opt/mssql/data
    environment:
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "4433:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1'  -b -o /dev/null"
        ]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 300s
      start_interval: 10s
volumes:
  fed-assignment2:
    name: fed-assignment2-db
