// Base interface defining the core structure of an exam
// This contains all the fundamental information needed to define an exam
export interface Exam {
  id: string;                      // Unique identifier for the exam
  examtermin: string;              // Exam term/period (e.g., "sommer 25", "vinter 24")
  courseName: string;              // Name of the course being examined
  date: string;                    // Exam date in YYYY-MM-DD format
  startTime: string;               // Start time in HH:MM format
  numberOfQuestions: number;       // Total questions available for random selection
  examDurationMinutes: number;     // Allocated time per student in minutes
  students?: Student[];            // Optional array of students registered for this exam
}

// Interface for creating a new exam
// Omits the 'id' field since it's generated by the system
export interface CreateExamData {
  examtermin: string;              // Exam term/period
  courseName: string;              // Course name
  date: string;                    // Exam date
  startTime: string;               // Start time
  numberOfQuestions: number;       // Number of questions available
  examDurationMinutes: number;     // Duration per student
}

// Interface defining a student participating in an exam
export interface Student {
  id: string;                      // Unique identifier for the student
  exam: string;                    // ID of the exam this student is registered for
  studenNo: string;               // Student number/ID from university system
  firstName: string;               // Student's first name
  lastName: string;                // Student's last name
  
  // Examination results - these fields are populated during/after the exam
  questionNo?: number;             // Question number that was randomly drawn (1-based)
  grade?: string;                  // Final grade assigned (e.g., "12", "10", "7", etc.)
  examDurationMinutes?: number;    // Actual time spent in examination (minutes)
  notes?: string;                  // Examiner's notes and observations
}

// Interface for creating a new student
// Omits system-generated fields and examination results
export interface CreateStudentData {
  exam: string;                    // ID of the exam to register student for
  studenNo: string;               // Student number from university system
  firstName: string;               // Student's first name
  lastName: string;                // Student's last name
} 